#!/usr/bin/env python3
"""re-save_models.py — re-serialize xgboost bundles in the CURRENT format.

The bundles were pickled by an older xgboost; loading prints the
'configuration generated by an older version of XGBoost' warning and works
only through a compat path. This script re-serializes each booster via the
current Booster.save_model/load_model format and REBUILDS the sklearn
wrapper around it, then verifies head-level predictions are bit-identical
before writing. Aborts any file whose predictions differ.

Usage: ./.venv/bin/python re-save_models.py [--only ema_cross_chronos.joblib]
"""
import argparse
import glob
import os
import sys

import joblib
import numpy as np
import xgboost as xgb
from xgboost import XGBClassifier, XGBRegressor

HERE = os.path.dirname(os.path.abspath(__file__))
rng = np.random.RandomState(7)


def rebuild_head(name, head, X) -> bool:
    """Re-serialize the booster inside `head`; swap in a fresh-format wrapper.
    Returns True on bit-identical head predictions (checked pre/post)."""
    clf = getattr(head, "_clf", None) or getattr(head, "_reg", None)
    if clf is None or not hasattr(clf, "get_booster"):
        return False
    is_clf = hasattr(head, "_clf") and head._clf is not None

    before_proba = None
    try:
        before = head.predict(X)
        if is_clf and hasattr(head, "predict_proba"):
            before_proba = head.predict_proba(X)
    except Exception as e:
        print(f"  ! {name}: pre-check failed: {e}")
        return False

    tmp = os.path.join(HERE, "models", f".tmp_{name}.json")
    booster = clf.get_booster()
    booster.save_model(tmp)                     # current format (JSON)
    b2 = xgb.Booster()
    b2.load_model(tmp)

    # raw-booster equality (bit-exact, float32)
    d = xgb.DMatrix(X)
    raw_eq = np.array_equal(booster.predict(d), b2.predict(d))

    # fresh wrapper in current format
    wrapper = (XGBClassifier() if is_clf else XGBRegressor())
    wrapper.load_model(tmp)
    os.remove(tmp)

    if is_clf:
        head._clf = wrapper
    else:
        head._reg = wrapper

    after = head.predict(X)
    after_proba = head.predict_proba(X) if (is_clf and before_proba is not None) else None
    proba_eq = (after_proba is None) or np.array_equal(before_proba, after_proba)
    pred_eq = np.array_equal(before, after)
    ok = raw_eq and pred_eq and proba_eq
    if ok:
        print(f"  ✓ {name}: re-serialized; raw/pred/proba all bit-identical")
    else:
        print(f"  ✗ {name}: raw_eq={raw_eq} pred_eq={pred_eq} proba_eq={proba_eq} — ABORT file")
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default=None, help="process a single bundle filename")
    args = ap.parse_args()

    pat = os.path.join(HERE, "models", args.only or "*_chronos.joblib")
    paths = sorted(glob.glob(pat))
    ok_all = True
    for path in paths:
        name = os.path.basename(path)
        print(f"== {name}", flush=True)
        try:
            bundle = joblib.load(path)
        except Exception as e:
            print(f"  LOAD FAILED: {e} — skipping")
            continue
        X = rng.randn(64, bundle.get("feat_dim", 337)).astype(np.float32) * 3.0
        heads = [k for k in bundle if isinstance(bundle[k], object)
                 and hasattr(bundle[k], "predict")
                 and (hasattr(bundle[k], "_clf") or hasattr(bundle[k], "_reg"))]
        ok = True
        for k in heads:
            ok = rebuild_head(f"{name}.{k}", bundle[k], X) and ok
        if ok:
            joblib.dump(bundle, path)
            print(f"  ✅ wrote {path}")
        else:
            ok_all = False
            print(f"  ⏭ {name} untouched (predictions not identical)")
    print("\nDONE", "ALL OK" if ok_all else "SOME ABORTED")
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
